import type { Metadata } from 'next'
import './globals.css'
import { Prata } from 'next/font/google'
import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/footer'

const prata = Prata({
	weight: ['400'],
	subsets: ['latin', 'cyrillic'],
	display: 'swap'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={prata.className}>
				<Header />
				<main className='flex min-h-[100dvh] flex-col border-y'>
					{children}
				</main>
				<Footer />
			</body>
		</html>
	)
}
